### ISSUE TITLE
[React] Add Bucket Tip View

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#134]
Build the bucket tips tab view. 

* Display the number of tips in the last 24 hours
* Display a plot of the number of tips over the course of time

**Comment by mlp6** [comment]
Also keep track of servo (valve) activation over that same time period.

**Comment by aforbis-stokes** [comment]
I think we should go ahead and apply a constant unit conversion for that displayed average value for last 24 hours. That is each tip = 0.325 Liter. I was hesitant before because that value changes slightly between sites, but I think the final unit being displayed as L / day instead of tips / day is much more useful to anyone looking at the website. I can fine-tune on the back end with exact volume for location
