### ISSUE TITLE
Develop 'reset' of the system functionality in constructor and method

### ISSUE THREAD

**Issue by DanielHull** [mlp6/ADPL#143]
I wonder if I can save a flow_position variable to the EEPROM or some storage compartment so it knows how many turns to make to get back to 'home'

**Comment by DanielHull** [comment]
maybe particle.variable???

**Comment by suyashkumar** [comment]
@DanielHull Do we still intend to use contact switches on either extreme of the linear stepper's range of motion? I think it'd be good to have some crude physical feedback in addition to a software persistent storage solution in case the stored value is somehow corrupted or wrong (I know it's high torque, but is it possible for someone to physically move the stepper by accident?). Though it adds complexity so might not be good for now, but if we see issues also consider coupling a potentiometer to the motion of the stepper in the future. 

Software-wise, the electron has [emulation EEPROM](https://docs.particle.io/reference/firmware/electron/#eeprom) that actually persists data to flash memory :). You should be able to write a step count or distance to home value here. Something to consider next is how often you wish to write this value (every N steps?). Luckily, since this isn't EEPROM, you will not suffer wear on each write to an address but "only when the page fills up"--look more into this.

**Comment by DanielHull** [comment]
@suyashkumar thanks Suyash, I think we could definitely implement them.

 I think I found a way to do it without monitoring the position of the pinch valve. I create an array of the most recent 6 bucket tip updates, which at every 2.5 minutes, allows me to calculate the flow rate over the past 15 minutes (calculates # buckets/hour). Once it moves towards extremes from the target flow rate, the clamp does it's job. Haven't tried with the Duke ADPL yet though, in this way if there are no bucket tips at all, the feedback is to open it back up.
