### ISSUE TITLE
[React Client] git-configurable "Notes" section per ADPL site

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#154]
Construct a notes view that shows some preset notes for a given ADPL site. The notes data is stored in a fixed JSON file that can be edited by @aforbis-stokes.

**Comment by suyashkumar** [comment]
@aforbis-stokes @mlp6 is there a future use case where we would actually want to serve these notes from the server? Would we want these configurable via a user interface? If the goal is to just have notes set via commits to the repo (since this is likely a short term thing) I will just bake the messages into the front-end code -- no need for the server to send 'em down. Not the best technical design, but this might suit our use case just fine.

**Comment by aforbis-stokes** [comment]
I can't think of a need for that for now. I really only see this being used by me to explain any abnormalities that the user may see on a per-location basis. Part of the danger of sharing all of our data is someone misinterpreting b/c they do not know the full picture (ie. I don't want someone external to check in and think our whole concept has failed b/c the temps are low, when the reality is that we are doing some maintenance.)

**Comment by suyashkumar** [comment]
@aforbis-stokes that sounds great and makes a lot of sense. I'll get this notes section done by Monday or Tuesday!
