### ISSUE TITLE
reduce cellular data usage

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#29]
@aforbis-stokes estimated current data usage for 2.5 min publish events for 5 temperature probes to be ~13.2 MB/month, which will not be cheap.  Some ideas to reduce this data usage are to reduce the precision of data being published, maybe report stats over larger time intervals.

**Comment by mlp6** [comment]
@aforbis-stokes looked into the data overhead associated with every publish event, which appears to be non-trivial, so we will accumulate data for every 1-2 hours and publish then.

**Comment by suyashkumar** [comment]
This makes sense! Can I suggest we build the following JSON publish string: 
"[
    {10:<temp>, 11:<temp>, ...,time:<UTC time>},
    {10:<temp>, 11:<temp>, ..., time:<UTC time>}
]" 
Note that we can save 300 bytes off the bat by still publishing every 2.5 minutes (which is a nice "heartbeat" to have) by incorporating the 4 thermistors' data into one publish string like
"{10:<temp>, 11:<temp>, ...}" . We can leave out the outer braces to save 2 bytes a message too (I can deal with that on server-side).

**Comment by mlp6** [comment]
Sounds like a great plan to me.

**Comment by mlp6** [comment]
https://docs.particle.io/guide/getting-started/data/electron/

**Comment by suyashkumar** [comment]
Note the additional 318 bytes an hour that are being spent keeping the cell connection alive. I don't think we should be opening and closing the cell connection anymore though, cause we lose on demand access and control ability, but figured this would be good to note

**Comment by suyashkumar** [comment]
@mlp6, @aforbis-stokes:
Just bumping this thread over here. To save data and prevent us from worrying about publish rate limits, are we still interested in publishing all temps at once with, say a TEMP event with the following payload:
"
{
    "HTR":  [Number],
    "HXCI": [Number],
    ...
}
"
I think that makes sense since doing separate publishes for each temp causes us an extra 300 bytes a publish every time and (if I understand correctly) there's no reason we'd only want to publish one temp and not others? 
Would be happy to impl this on both the firmware and the server side if people are busy.

**Comment by mlp6** [comment]
There are still some sub-par syntax in play for parsing the TEMPS event... the JSON is malformed, so I cannot just use `JSON.parse()` to build a dictionary from these data that I can just loop over.  I need to fix that.

**Comment by mlp6** [comment]
Actually, in thinking about it a tad more, publishing a true JSON string is going to require even more characters to transmit, so I will leave it as is (for now).
