### ISSUE TITLE
npm error on Docker config to build frontend static assets on start

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#305]

**Comment by mlp6** [comment]
```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/app/react-client/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.1.7-300.fc30.x86_64
gyp ERR! command "/usr/local/bin/node" "/app/react-client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /app/react-client/node_modules/node-sass
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by mlp6** [comment]
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
```

**Comment by mlp6** [comment]
[log.txt](https://github.com/mlp6/ADPL/files/3286128/log.txt)

this is a copy of the full build log that was generated

**Comment by mlp6** [comment]
Note that manually running the `npm install` command works just fine.

**Comment by suyashkumar** [comment]
Interesting, running `docker compose up --build` worked fine on my Mac and I was able to test end to end. This appears to be a build error building libsass. I can look deeper into the logs when I’m not on my phone but this makes me wonder if using `FROM node:latest` is a bad idea (maybe if we use the old tag, it’ll be able to pull a prebuilt version of libsass, which is known to have build issues). 

Can you give me the specs on your machine, since I can’t reproduce this on my Mac?

**Comment by suyashkumar** [comment]
Also, there are a lot of old and deprecated deps in this repo that would be nice to update and cleanup in the future (and update to the latest react).

**Comment by suyashkumar** [comment]
Try modifying the dockerfile to use `FROM node:7.8.0` which is the base image the frontend container used previously—I cannot reproduce on my system (maybe could on a vm) otherwise I’d test myself.
