### ISSUE TITLE
Particle unstable?

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#71]
Marc mentioned a few weeks ago over email that he considered the Particle units to be "unstable", but when I asked for more detail to support that statement, I never heard anything back.  Do you know what he was referring to in making this statement?

**Comment by aforbis-stokes** [comment]
I think it was a response to the combination of our difficulties, which I do not believe are due to the Particle, as well as difficulties another lab in our department has had (Mike Bergin if you know him). I am not sure what problems they have had, though. I'll try to get more feedback from them, but I still prefer working with Particle.

**Comment by mlp6** [comment]
I'm going to close this issue since I think we're confident that we've identified the primary problems with the field units.  Feel free to re-open if you disagree.
