### ISSUE TITLE
Update schematic with new relays 

### ISSUE THREAD

**Issue by oo22** [mlp6/ADPL#99]
the schematics in the repository include the schematic representation of the old relays that we were using. Need to update the schematic with the schematic representation of the new relays that we are using.

**Comment by mlp6** [comment]
@DanielHull can you check that these relays are correct, and if so, close this out?

**Comment by aforbis-stokes** [comment]
The most recent commit I made "ADPL_improved" has a few changes from the last schematic other than just relay. By-pass capacitors for relays were put into a different location (on + side of relay), and protection diodes were put onto each input sensor. Also, the old igniter was replaced by the new igniter that does not spark and uses 12V and 2A (peak of 7A). @DanielHull looking over the recent diagram with the comments from the Greg Mimmack report in mind would be helpful.
But, but back the relay conversation. I checked the relay part number on the diagram, and I forgot to update it to 817-FTR-F1CL012R (specified up to 8A as needed for relay). These are the relays we wanted to switch to because of the high dielectric and surge strength that could protect against igniter shorts. However, changing the igniter resolves this problem (spark igniter = 10kV; surface igniter = 12V), and the old relays may be fine (https://www.amazon.com/gp/product/B00PFA83RW/ref=oh_aui_search_detailpage?ie=UTF8&psc=1). 
I'm open to either version. If we wanted the relays on a custom board, the FTR makes sense. If we want to keep the relays on a separate board from the controller, the Amazon board may be easiest. Thoughts?

**Comment by DanielHull** [comment]
@aforbis-stokes the review also mentioned the carrying capacity of the lines as a concern. Not sure if that was something before the ones on Amazon, but the ones listed above carry 10A. Do you where the data sheet for that is? Couldn't identify it on Amazon or online...

**Comment by aforbis-stokes** [comment]
This is the best I've found (relay only, does not include board)
https://www.ghielectronics.com/downloads/man/20084141716341001RelayX1.pdf

**Comment by DanielHull** [comment]
There are a lot of similarities (similar coil rating, voltage range, and carrying current). Of note is that one is a DPDT (FTR-F1CL012R) the other two SPDT. The Fujitsu relay is much smaller overall. The only question is control. I'd have to look in more if one signal causes both to switch, (whether we even want that...) or whether there is independent control of both poles.
